version: '3.8'
name: expense
networks:
  default:
      name: expense
services:
  mysql:
    image: mysql
    container_name: mysql
  backend:
    image: backend
    command: sh -c "sleep 20 && node /opt/server/index.js"
    depends_on:
      - mysql
  frontend:
    image: frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"